-- Superseded by 006_notify_seen.sql on 2026-08-07.
--
-- This file created notify_watermark for the Telegram notifier, which no longer
-- exists. Its statements are removed rather than the file, because 006 seeds
-- from notify_watermark when it is present and this directory is re-run whole
-- on every initdb — leaving the CREATE here would resurrect the table after 006
-- had read it.
--
-- The table itself is dropped in a later migration, once the seed has been
-- confirmed correct on both databases.
